### ISSUE TITLE
GLES2 compatibility

### ISSUE THREAD

**Issue by CangurinLimpiezasZaragoza** [QueenChristina/gd_dialog#1]
Hi!
I use your gd_dialog for my prototype proyect in android,
i use GLES2, when i export the proyect to android  all is ok,
but in the game, when the dialog is open the dialog are empty, without letters,
any idea? so much thanks

**Comment by QueenChristina** [comment]
> Hi!
> I use your gd_dialog for my prototype proyect in android,
> i use GLES2, when i export the proyect to android all is ok,
> but in the game, when the dialog is open the dialog are empty, without letters,
> any idea? so much thanks

Hi!
Thank you so much for using my dialog system, and thank you also for bringing this issue up. 

When you export the game, did you also make sure to [export all non-game specific resources](https://godotengine.org/qa/47956/export-not-including-non-resource-files)? The system uses .json file and font resources, so it’s possible nothing shows up if the .json file is not being exported with the game.

![image](https://user-images.githubusercontent.com/31525446/133882786-4dbe7844-047c-4eea-bf8d-13d102bfd17d.png)

Also, if you exported with debugger, what error messages pop up?

Good luck with your game! :)

**Comment by CangurinLimpiezasZaragoza** [comment]
is a json problem, thanks so much, and thanks for open for the proyect too.

**Comment by QueenChristina** [comment]
You're welcome! Happy to hear your issue was resolved!
