### ISSUE TITLE
import UI scene to proyect

### ISSUE THREAD

**Issue by CangurinLimpiezasZaragoza** [QueenChristina/gd_dialog#2]
Hi, I have a doubt -

i use the gd_dialog in your example , i try my custom changes and all is perfect.
but in the moment of import / implement in my own proyect , i have a little trouble.

i copy the UI folder in the root of my proyect,
i copy the folder GameSrc and activate in autoload the four singletons(UI.tscn...)
i copy the Data folder
i respect your tree structure and copy the Assets dependencies

i instantiate UI in my "World scene" proyect

but i get  one error of "The identifier UI isnt declared in the current scope" when i play f6

is this way the correct way for implement? or i loss someting? sure is the second, 

thanks for any help

![Captura de pantalla de 2021-10-02 15-58-56](https://user-images.githubusercontent.com/32023336/135720824-07b045ef-9fed-439f-9725-ff575bb74be7.png)

**Comment by QueenChristina** [comment]
Hi! Thanks for letting me know of this issue.

Did you make sure that UI.tscn is added as a global autoload singleton, under the exact name of "UI"? Make sure it is spelled the exact same. You can modify [autoloads ](https://docs.godotengine.org/en/stable/getting_started/step_by_step/singletons_autoload.html)under Project Settings.
![image](https://user-images.githubusercontent.com/31525446/135738890-f42bdc82-1f38-491a-b606-6ae93c4222f5.png)

**Comment by CangurinLimpiezasZaragoza** [comment]
Thanks for rsponse QueenChristina.
Yes, i am sure :(
![Captura de pantalla de 2021-10-03 11-59-57](https://user-images.githubusercontent.com/32023336/135750332-12fd7a94-b47c-479e-9803-c435aefbe9c3.png)

**Comment by QueenChristina** [comment]
I believe it is case-sensitive, so make sure the name of the singleton matches EXACTLY.

Right now, UI.tscn is called "Ui" in your picture, but it should actually be named "UI" to match what is in the code (the second letter should be capitalized).

**Comment by CangurinLimpiezasZaragoza** [comment]
its true, "Ui" for "UI" solve the error.
Many thanks QueenChristina, i am happy for solve this problem, now i can continue with me history game with your fantastic dialog system.

**Comment by QueenChristina** [comment]
Happy to help! Have fun making your game.

**Comment by RuslanFlash** [comment]
OH MY GOD, i tried to solve this problem for 5 hours, and now when i know what was the problem, i just want to forgot this day, thank you so much really
