### ISSUE TITLE
utf8 problem

### ISSUE THREAD

**Issue by CangurinLimpiezasZaragoza** [QueenChristina/gd_dialog#3]
Hi, i want insert special characters like "ñ" in the json file, i try insert in unicode (\u00F1), but dont works, 
i think that in Globals.gd in

file.open(file_name, file.READ)
var file_content = parse_json(file.get_as_text())

how i can convert in utf8 "file_content"?

many thanks

**Comment by QueenChristina** [comment]
Hi! 
A few possible fixes:

- Ensure the font you use in your game supports these special characters. As a note, the font used in the example is a custom one I made, but it doesn't support special characters (so nothing shows up if you type it in). Try changing the font to a default font or another font that supports these characters.
![image](https://user-images.githubusercontent.com/31525446/138531202-fe7a13e3-3361-418c-998b-6d9b04c4ae12.png)

- Copy-paste the special character "ñ" into your json file, not the unicode itself.
![image](https://user-images.githubusercontent.com/31525446/138531408-3e102c22-e4b5-485c-a2e3-dc60682e54f3.png)

- Double check the file in which you save your dialogue data is utf-8 encoded and a .json file.

Thank you so much for bringing all these issues to my attention. I really appreciate your help making this system better, and I'm sure it will help others who encounter the same issues as you. :)

**Comment by CangurinLimpiezasZaragoza** [comment]
Many thanks, **change the font to a default font** solve the problem easy.
Thank so much too for your work, this dialog system is many flexible for all that i need for my proyects, and i think too that is the most powerfull system godot dialog actually.

**Comment by QueenChristina** [comment]
> Thank so much too for your work, this dialog system is many flexible for all that i need for my proyects, and i think too that is the most powerfull system godot dialog actually.

Aw, thank you so much! It always makes my day seeing your comments. Best of luck to you on your projects.
