### ISSUE TITLE
Resizable Dialog box

### ISSUE THREAD

**Issue by Xarcaneo** [QueenChristina/gd_dialog#5]
Hi, I don't know how to resize my Dialog Box to be smaller and fits my game resolution, I can only make it bigger but it is not possible to make it smaller. I can make it smaller only by use scale, I would like to make the whole textbox like 0.6 scale but I think this way is not proper way to set it, especially if I will make avatars for game it will be not okay.

**Comment by QueenChristina** [comment]
Hi,
Great question! The dialog box (at res://UI/dialog/dialog.tscn) right now has a minimum size set for the Panel Container holding the character icon, so you will need to decrease that minimum size to fit the size of the icon/avatar of your game's dialog box (see res://UI/dialog/animated_sprite_container.gd for more info on how the icons are positioned).
You may also want to play around with decreasing the margins of the current dialog box.

![image](https://user-images.githubusercontent.com/31525446/147615672-8ef40ff3-b2c9-4fa5-9e9c-e1e34764f33c.png)
![image](https://user-images.githubusercontent.com/31525446/147615677-166b6a4e-fd01-4c7d-b253-84b9d8ced0c8.png)

Please let me know if you have any more questions! Good luck on your game.
